### ISSUE TITLE
Workaround for Mantis #2280

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/pivy#23]
https://freecadweb.org/tracker/view.php?id=2280
Upstream coin3d is very slow to respond. Is there a workaround that can be done on the FC side ?

**Comment by looooo** [comment]
it works for me on ubuntu 17.04 and daily builds. No idea what to do about it.

**Comment by luzpaz** [comment]
@looooo basically you're saying you can't reproduce the issue? If so can you annotate the mantis ticket?

**Comment by looooo** [comment]
done.
