### ISSUE TITLE
Missing fake headers

### ISSUE THREAD

**Issue by Grawp** [FreeCAD/pivy#42]
https://bitbucket.org/Coin3D/coin/commits/9fdee54b54682a99b1e831a12fe5e193141d3c05 changed many of the std library includes to C++ style ones. Fake headers for _cstddef_, _cstdarg_, _cassert_ are missing.

**Comment by J-Dunn** [comment]
Many thanks, I'll look into that.

**Comment by J-Dunn** [comment]
```
# some missing fake headers since recent change to cstyle headers
pivy-master/fake_headers
touch cstddef cstdarg cassert
```

seems to be compiling now ...  at least it's stopped bitching about cstddet et al ;)

**Comment by looooo** [comment]
Thanks,
Somehow I forgot to add it to this library.
https://github.com/FreeCAD/pivy/pull/46
