### ISSUE TITLE
pythoin pivy install error

### ISSUE THREAD

**Issue by kelargo** [FreeCAD/pivy#51]
I am using the freecad stable PPA in xubuntu.  It use to install and work fine, but recently I started getting an error regarding python-pivy.   text styling below is kind of ugly.. 

what other info can I provide?   seems like some example file is corrupt?  
./usr/share/doc/python-pivy/examples/Mentor/oak.rgb.gz'

> 
# apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  libsoqt4-20 python-qt4-gl
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  python-pivy
The following NEW packages will be installed:
  python-pivy
0 upgraded, 1 newly installed, 0 to remove and 49 not upgraded.
1 not fully installed or removed.
Need to get 0 B/2,493 kB of archives.
After this operation, 15.1 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
dpkg: warning: files list file for package 'libldb1:amd64' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'liblightdm-gobject-1-0:amd64' missing; assuming package has no files currently installed
(Reading database ... 527154 files and directories currently installed.)
Preparing to unpack .../python-pivy_0.6.4-0ppa2~ubuntu18.04_amd64.deb ...
Unpacking python-pivy (0.6.4-0ppa2~ubuntu18.04) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/python-pivy_0.6.4-0ppa2~ubuntu18.04_amd64.deb (--unpack):
 cannot copy extracted data for './usr/share/doc/python-pivy/examples/Mentor/oak.rgb.gz' to '/usr/share/doc/python-pivy/examples/Mentor/oak.rgb.gz.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 /var/cache/apt/archives/python-pivy_0.6.4-0ppa2~ubuntu18.04_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by kelargo** [comment]
can you think of any work around?   I'm not sure why this example program is even needed?

**Comment by kkremitzki** [comment]
> can you think of any work around? I'm not sure why this example program is even needed?

It's part of the package. It should eventually be split out into `python-pivy-doc` and made optional. It seems like your download was corrupted. Try removing the cached package file `/var/cache/apt/archives/python-pivy_0.6.4-0ppa2ubuntu18.04_amd64.deb` and updating again.

**Comment by kelargo** [comment]
ok, thanks.  that worked.  

I removed two version..  freecad is happy again. 

```
python-pivy_0.5.0~v609hg-4_amd64.deb
python-pivy_0.6.4-0ppa2~ubuntu18.04_amd64.deb
