### ISSUE TITLE
Error loading libCoin library.

### ISSUE THREAD

**Issue by BlGene** [FreeCAD/pivy#54]
Following the instructions from: https://www.freecadweb.org/wiki/Python_3, specifically the `Test builds on anaconda (linux64)` part.

I get the following error:
```
>>> import pivy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/acct/local/miniconda3/envs/freecad_py3/lib/python3.6/site-packages/pivy/__init__.py", line 30, in <module>
    from .coin import SoDB, SoNodeKit, SoInteraction
  File "/home/acct/local/miniconda3/envs/freecad_py3/lib/python3.6/site-packages/pivy/coin.py", line 21, in <module>
    from . import _coin
ImportError: libCoin.so.80: cannot open shared object file: No such file or directory
```

These are the conda package versions:
```
coin3d                    4.0.0                h83d4a3d_4    conda-forge
pivy                      0.6.5a2          py36hc9558a2_0    conda-forge
```

I have the following file:
`/home/acct/local/miniconda3/envs/freecad_py3/lib/libCoin.so.4.0.0`

If I create a softlink from libCoin.so.4 -> libCoin.so.80 I get the following error:
```>>> import pivy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/acct/local/miniconda3/envs/freecad_py3/lib/python3.6/site-packages/pivy/__init__.py", line 30, in <module>
    from .coin import SoDB, SoNodeKit, SoInteraction
  File "/home/acct/local/miniconda3/envs/freecad_py3/lib/python3.6/site-packages/pivy/coin.py", line 21, in <module>
    from . import _coin
ImportError: /home/acct/local/miniconda3/envs/freecad_py3/lib/python3.6/site-packages/pivy/_coin.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK7SbPList4findEPKv
```

This is preventing me from doing a '.obj' export, which I hope will include mesh colors.

**Comment by looooo** [comment]
this instructions are not uptodate. Please add `freecad/label/dev` to the channel section instead of `freecad` or use freecad0.18 from conda-forge directly (by removing the freecad-channel from condarc).

btw.: pivy 0.6.5a2 needs coin4.0.0 h9b6af50_1005.

I hope this helps

**Comment by BlGene** [comment]
@looooo  Did you mean freecad-0.19 instead of freecad0.18 (freecad/label/dev/linux-64::freecad-0.19.pre-py37h648b96a_9)?

This is what worked for me, giving me the right pivy/coin combination. Also the the `python=3.6` is not suitable as this goes to 3.7.

**Comment by looooo** [comment]
Sry for having all the different versions available. I don't think it makes sense to explain all the differences. Simple stick with the weekly 0.19 builds which depend on py37. (I guess this is the package you have currently installed.)
